### ISSUE TITLE
VMAX Integration

### ISSUE THREAD

**Issue by metabsd** [ktelep/EMC-Zabbix-Integration#1]
Hi,

I love your project :) I want to know if you plan to integrate VMAX support. I will read your code and try it by my self.

Have a nice day!!

**Comment by ktelep** [comment]
Right now I don't have plans to add VMAX support, but it would be trivial to do.   I'm working on refactoring some of the code to make enhancements like that easier.    

What specific metrics would you want to measure on the VMAX?
