### ISSUE TITLE
Zabbix 3.0 not work

### ISSUE THREAD

**Issue by naechin91004** [ktelep/EMC-Zabbix-Integration#10]
I install zabbix 3.0 But template not work.

below is result.

info from server: "processed: 0; failed: 250; total: 250; seconds spent: 0.002306"
info from server: "processed: 0; failed: 19; total: 19; seconds spent: 0.000198"
sent: 269; skipped: 0; total: 269

zabbix trapper not receive data.

JSON output is valid but template return "Value should be a JSON object."

**Comment by ktelep** [comment]
It looks like the discovery did not complete, as it wasn't able to locate the keys in Zabbix to send the data to.

Can you post the output of the emc_vnx_discovery.py script when run as the zabbix user from the command line, and if you can attach/send a debug log from your 3.0 install that would help troubleshoot.

**Comment by ktelep** [comment]
Closed based on no feedback to resolve issue
