### ISSUE TITLE
Uncaught exception: 'module' object has no attribute 'SSLTimeoutError'

### ISSUE THREAD

**Issue by Sinezere** [ktelep/EMC-Zabbix-Integration#14]
Hi when i executed de script etc_vnx_discovery.py in the logs i can see this errors...

2016-06-22 18:17:32,506 INFO 31948 Building WBEM Connection to https://192.168.1.225:5989
2016-06-22 18:17:32,506 INFO 31948 Array hardware discovery started
2016-06-22 18:17:32,512 ERROR 31948 Uncaught exception: 'module' object has no attribute 'SSLTimeoutError'

Can i help me?

Best regards!

**Comment by Sinezere** [comment]
I solve it removing SSLTimeoutError in /usr/lib/python2.7/dist-packages/pywbem/cim_http.py file at:
------except ( Err.SSLError, SSL.SSLError, SSL.SSLTimeoutError-------

Thanks!

**Comment by ktelep** [comment]
Glad you worked around the issue but can you provide me with the version of
Python and pywbem you have on your system? You should not have to edit the
pywbem source.

**Comment by Sinezere** [comment]
I Use pywbem_0.8.0~dev650-1 and python 2.7. Now there are an other problem. I can't execute discovery shell script but zabbix shows "Value should be a JSON object." in discovery rules items...when execute de stats script receive this: zabbix_sender [30534]: Warning: incorrect answer from server [ZBX_NOTSUPPORTED] Sending failed. Use option -vv for more detailed output. Thank you
