### ISSUE TITLE
Issues with Zabbix 3.0

### ISSUE THREAD

**Issue by cspnanda** [ktelep/EMC-Zabbix-Integration#16]
While running the code with Zabbix 3.0 I get this error

2016-06-29 22:38:50,546 ERROR 4282 Uncaught exception: local variable 'timestamp' referenced before assignment

I am running it as 

/usr/lib/zabbix/externalscripts/emc_vnx_stats_debug.py --serial <SERIAL> --ecom_ip <IP> --ecom_user admin --ecom_pass #1Password --poolperf "<Pool Name>"

This was working fine with Zabbix 2.0

**Comment by ktelep** [comment]
Is there any way you can run it from the command line and give me the full stacktrace of the failure that would be great.  It's strange that it's throwing this exception.   

I noticed that the script is named _debug.py, have you made any modifications to it that may have also caused this error to be raised?
