### ISSUE TITLE
Value should be a JSON object

### ISSUE THREAD

**Issue by denisgubin** [ktelep/EMC-Zabbix-Integration#19]
in zabbix web 
discovery script error : Value should be a JSON object

**Comment by ktelep** [comment]
Can you provide the information in the discovery log file that should be found in /tmp.   There are a number of reasons that this error coudl occur.

**Comment by denisgubin** [comment]
Hi!

My system:
opensuse
python-pywbem-0.7-26.1.2.x86_64
python-2.7.6-8.22.1.x86_64

if run the script (emc_vnx_discovery.py and emc_vnx_stats.py) in the manual under user zabbix server (zabbixs), then all is well, I get the data from the SMI-s server: files appear in /tmp directory like , /tmp/emc_vnx_discovery. log and others. 
The rights to the script in the folder /externalsrcipts/: 
emc_vnx_discovery.py using getfacl commands
file#: emc_vnx_discovery.py
owner#: zabbixs
group#: zabbixs
user::rwx on
group::R-X
other::R-X

emc_vnx_stats.py using getfacl commands
file#: emc_vnx_stats.py
owner#: zabbixs
group#: zabbixs
user::rwx on
group::R-X
other::R-X
If configure the web-interface of zabbix-server, the log files in /tmp are not created .
The user zabbix server (zabbixs) :

cat /etc/passwd | grep zabbixs
zabbixs:x:496:493:Zabbix Server Daemon:/var/lib/zabbixs:/bin/false

run script manual from root, but:

 su -s /bin/bash -c '/usr/lib/zabbix/externalscripts/emc_vnx_discovery.py -s SERIAL NUMBER ARRAY  -i IP-ADDRESS SMI-S server --ecom_user admin --ecom_pass=#1Password -d' zabbixs

cat /tmp/cat emc_vnx_discovery.log

2016-09-12 12:53:28,162 INFO 16209 Building WBEM Connection to https://IP-ADDRESS SMI-S:5989
2016-09-12 12:53:28,163 INFO 16209 Disk discovery started
2016-09-12 12:53:29,622 INFO 16209 Generating output
2016-09-12 12:53:29,625 INFO 16209 Discovery Complete

But in zabbix web:

![screen](https://cloud.githubusercontent.com/assets/22106772/18431705/e9935d42-78e6-11e6-9c60-5f56b8861534.JPG)

and don't create log-file: /tmp/cat emc_vnx_discovery.log

**Comment by ktelep** [comment]
Can you confirm the user macros are set and also that the serial number is
set in the host field of the device inventory?

It seems like an execution problem so you may need to check the debug log
for the Zabbix server to see if it's running into a problem executing the
script

**Comment by denisgubin** [comment]
Am I right?

![screen 4](https://cloud.githubusercontent.com/assets/22106772/18436314/613a8b0e-7900-11e6-8de2-37df0f480fb0.JPG)
![screen 5](https://cloud.githubusercontent.com/assets/22106772/18436315/65af0ef8-7900-11e6-938e-e0f37300019d.JPG)
![screen 6](https://cloud.githubusercontent.com/assets/22106772/18436317/6965bd08-7900-11e6-988e-2ba2d108c042.JPG)

**Comment by ktelep** [comment]
Everything looks correct, which makes me think that either it is not able
to execute the script for some reason, or it's immediately dying when it
tries to run.
1.  It may have been a typo, but I noticed that you referenced
   /externalsrcipts/,
   which has the c and r swapped in the directory name.
2.  Confirm that the externalscripts directory has all the necessary
   permissions for the zabbixs user
3.  Confirm that the zabbix server is actually running as the zabbixs user
4.  Increase the Zabbix log level to either debug or trace (levels 4 or 5)
   and let it run for about 30 minutes, then go through the log to see if
   there is an error that Zabbix is throwing when it tries to execute the
   script.

**Comment by denisgubin** [comment]
solved the problem! 
if you look at the screenshot with Macros, you'll see that the values of the fields "ecomuser" and "ecompass" must be reversed. 
The funny thing is that I saw after the procedure zabbix-server debug :)
Many Thanks!
