### ISSUE TITLE
I can't get moniter

### ISSUE THREAD

**Issue by zbinbin** [ktelep/EMC-Zabbix-Integration#2]
When I follow your step to moniter my EMC VNXe3100,the zabbix latest data is :
Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/emc_vnx_stats.py", line 613, in <module>
    main()
  File "/usr/lib/zabbix/externalscripts/emc_vnx_stats.py", line 605, in main
    args.ecom_user, args.ecom_pass)
  File "/usr/lib/zabbix/externalscripts/emc_vnx_stats.py", line 330, in hardware_healthcheck
    array_list = ecom_conn.EnumerateInstanceNames("Clar_StorageSystem")
  File "/usr/lib/python2.6/site-packages/pywbem-0.7.0-py2.6.egg/pywbem/cim_operations.py", line 382, in EnumerateInstanceNames
    **params)
  File "/usr/lib/python2.6/site-packages/pywbem-0.7.0-py2.6.egg/pywbem/cim_operations.py", line 168, in imethodcall
    verify_callback = self.verify_callback)
  File "/usr/lib/python2.6/site-packages/pywbem-0.7.0-py2.6.egg/pywbem/cim_http.py", line 225, in wbem_request
    raise AuthError(response.reason)
pywbem.cim_http.AuthError: Authorization Required

what's wrong?

**Comment by ktelep** [comment]
First of all, I'm not sure how much of this will work on the VNXe, I'll have to dig and see whether the performance statistics are actually exposed by that array as compared to a VNX or VNX2.

So the last line in the traceback says that it is trying to authenticate to the ECOM server but is unable to.

Can you confirm
1.  The ECOM server is setup and running
2.  You successfully added the array to the ECOM server either via the script in the tools directory or using the testsmiprovider binary provided with it.

Try running the following and let me know if there is output:

```
emc_vnx_discovery.py --serial <array serial> --ecom_ip <IP adddress> -- ecom_user <ecom username> --ecom_pass <ecom password> --disks
```

If that works successfully, try adding the following macros to your host config:
  {$ECOMUSER}  -- The ECOM Username
  {$ECOMPASS} -- The ECOM password

**Comment by ktelep** [comment]
So in digging in the documentation it appears that the VNXe3100 is not supported by the standard ECOM SMI-S provider.  The VNXe3200 has a built in SMI-S provider however the CIM classes are currently not supported.

Also, the documentation has been updated in order to note the requirement to add the {$ECOMUSER} and {$ECOMPASS} user macros in Zabbix

**Comment by zbinbin** [comment]
Can you tell me how to install the EMC ECOM Server?

**Comment by ktelep** [comment]
You can download it via support.emc.com, just search for SMI-S provider.  However be aware that the VNXe3100 is not supported by the ECOM server and as such by this integration.
