### ISSUE TITLE
not enough data

### ISSUE THREAD

**Issue by behzad-kh** [ktelep/EMC-Zabbix-Integration#26]
Hi Ktelep

I am trying to integrate my Clariion with Zabbix. So far so good, and I would like to thank you for your time and effort for this integration.

Regarding to the question, I have added the HOST successfully and most of the items are enabled and are polling data. There are some items that was shown as "Not Support" in Zabbix 4.0, but I conquer them and resolve the issue, however, there are other items that I couldn't make them right.
Here is the problematic item:
"VNX Volumes: **THE_LUN_INFO** - Read Response Time" is shown as not supported and the the error message is cannot evaluate expression: **"cannot evalute function "last()": not enought data."**

The item formula is as follow:
(for security purpose I have changed the serial number to SERIAL_NUMBER)
_(last("emc.vnx.perf.EMCSampledReadsTime[CLAR+_SERIAL_NUMBER_+Volume+00000]")/(last("emc.vnx.perf.ReadIOs[CLAR+SERIAL_NUMBER+Volume+00000]"))/1000)_

In order to narrow down the problem, I have created other items in order to get values of the formula separately which is follow:
(last("emc.vnx.perf.ReadIOs[CLAR+SERIAL_NUMBER+Volume+00000]")) ==> It has 57 in the last value in Zabbix lastest data.

last("emc.vnx.perf.EMCSampledReadsTime[CLAR+_SERIAL_NUMBER_+Volume+00000]") ==> It shows no enough data as I said earlier. I believe that's the root cause of the problem.

I know it is long post, but I appreciated your help regarding this issue.

Thanks in advance
 Behzad

**Comment by ktelep** [comment]
EMCSampledReadsTime is not supported on the Clariion, only on VNX, which is why it has no data in it and you recieve this error.
