### ISSUE TITLE
The target namespace does not exist

### ISSUE THREAD

**Issue by pouyan13** [ktelep/EMC-Zabbix-Integration#29]
I'm having an error in the discovery rules, they pass the message "ERROR 18142 Uncaught exception: (3, u'The target namespace does not exist.')
this error generates in emc_vnx_discovery.log when  I ran it manually with below command
/emc_vnx_discovery.py --serial --ecom_ip 192.168.71.75 --ecom_user it --ecom_pass "P@ssw0rd" --procs

**Comment by ktelep** [comment]
This typically indicates an issue with the ECOM server, you may want to verify it's operating correctly, and that you're running this against a VNX not a VNXe.
