### ISSUE TITLE
Zabbix 3.0

### ISSUE THREAD

**Issue by tellurianx** [ktelep/EMC-Zabbix-Integration#4]
This Template works with zabbix 3.0? I made the installation but in the discovery rules zabbix shows an alert saying that Value Shoud Be a JSON object.

**Comment by ktelep** [comment]
I have not yet tested it with 3.0, please run the discovery script as the zabbix user from the command line of the server and provide the output.

**Comment by tellurianx** [comment]
The output is fine:

## ./emc_vnx_stats.py --serial CKM00120201237 --ecom_ip X.X.X.X --ecom_user admin --ecom_pass "#1Password" --proc

Current Time: Thu Jan 28 09:04:09 2016    Stat Time: Thu Jan 28 09:02:30 2016
info from server: "processed: 0; failed: 32; total: 32; seconds spent: 0.000532"
sent: 32; skipped: 0; total: 32
CKM00120201237 emc.vnx.perf.TotalIOs[CLAR+CKM00120201237+FEAdapt+SP-A] 1453978950 4349952197
CKM00120201237 emc.vnx.perf.KBytesTransferred[CLAR+CKM00120201237+FEAdapt+SP-A] 1453978950 142277901834
CKM00120201237 emc.vnx.perf.IOTimeCounter[CLAR+CKM00120201237+FEAdapt+SP-A] 1453978950 100324
CKM00120201237 emc.vnx.perf.ReadIOs[CLAR+CKM00120201237+FEAdapt+SP-A] 1453978950 481979614
CKM00120201237 emc.vnx.perf.KBytesRead[CLAR+CKM00120201237+FEAdapt+SP-A] 1453978950 74798658800
CKM00120201237 emc.vnx.perf.WriteIOs[CLAR+CKM00120201237+FEAdapt+SP-A] 1453978950 3867972583
CKM00120201237 emc.vnx.perf.KBytesWritten[CLAR+CKM00120201237+FEAdapt+SP-A] 1453978950 67479243034
CKM00120201237 emc.vnx.perf.IdleTimeCounter[CLAR+CKM00120201237+FEAdapt+SP-A] 1453978950 483532
CKM00120201237 emc.vnx.perf.EMCHighWaterFlushes[CLAR+CKM00120201237+FEAdapt+SP-A] 1453978950 22681
CKM00120201237 emc.vnx.perf.EMCLowWaterFlushes[CLAR+CKM00120201237+FEAdapt+SP-A] 1453978950 22681
CKM00120201237 emc.vnx.perf.EMCIdleWaterFlushes[CLAR+CKM00120201237+FEAdapt+SP-A] 1453978950 3637464
CKM00120201237 emc.vnx.perf.EMCWriteFlushes[CLAR+CKM00120201237+FEAdapt+SP-A] 1453978950 444660765
CKM00120201237 emc.vnx.perf.EMCWriteKBytesFlushed[CLAR+CKM00120201237+FEAdapt+SP-A] 1453978950 617653017
CKM00120201237 emc.vnx.perf.EMCQueueArrivals[CLAR+CKM00120201237+FEAdapt+SP-A] 1453978950 3334404224
CKM00120201237 emc.vnx.perf.EMCQueueLength[CLAR+CKM00120201237+FEAdapt+SP-A] 1453978950 127734447633
CKM00120201237 emc.vnx.perf.EMCPctDirtyPages[CLAR+CKM00120201237+FEAdapt+SP-A] 1453978950 73
CKM00120201237 emc.vnx.perf.TotalIOs[CLAR+CKM00120201237+FEAdapt+SP-B] 1453978950 1799862659
CKM00120201237 emc.vnx.perf.KBytesTransferred[CLAR+CKM00120201237+FEAdapt+SP-B] 1453978950 99862490172
CKM00120201237 emc.vnx.perf.IOTimeCounter[CLAR+CKM00120201237+FEAdapt+SP-B] 1453978950 3698511
CKM00120201237 emc.vnx.perf.ReadIOs[CLAR+CKM00120201237+FEAdapt+SP-B] 1453978950 195965769
CKM00120201237 emc.vnx.perf.KBytesRead[CLAR+CKM00120201237+FEAdapt+SP-B] 1453978950 43083831251
CKM00120201237 emc.vnx.perf.WriteIOs[CLAR+CKM00120201237+FEAdapt+SP-B] 1453978950 1603896890
CKM00120201237 emc.vnx.perf.KBytesWritten[CLAR+CKM00120201237+FEAdapt+SP-B] 1453978950 56778658920
CKM00120201237 emc.vnx.perf.IdleTimeCounter[CLAR+CKM00120201237+FEAdapt+SP-B] 1453978950 51354692
CKM00120201237 emc.vnx.perf.EMCHighWaterFlushes[CLAR+CKM00120201237+FEAdapt+SP-B] 1453978950 29507
CKM00120201237 emc.vnx.perf.EMCLowWaterFlushes[CLAR+CKM00120201237+FEAdapt+SP-B] 1453978950 29507
CKM00120201237 emc.vnx.perf.EMCIdleWaterFlushes[CLAR+CKM00120201237+FEAdapt+SP-B] 1453978950 2226138
CKM00120201237 emc.vnx.perf.EMCWriteFlushes[CLAR+CKM00120201237+FEAdapt+SP-B] 1453978950 337407076
CKM00120201237 emc.vnx.perf.EMCWriteKBytesFlushed[CLAR+CKM00120201237+FEAdapt+SP-B] 1453978950 563394386
CKM00120201237 emc.vnx.perf.EMCQueueArrivals[CLAR+CKM00120201237+FEAdapt+SP-B] 1453978950 206504761
CKM00120201237 emc.vnx.perf.EMCQueueLength[CLAR+CKM00120201237+FEAdapt+SP-B] 1453978950 65230760458
CKM00120201237 emc.vnx.perf.EMCPctDirtyPages[CLAR+CKM00120201237+FEAdapt+SP-B] 1453978950 65

---

But in the dashboard of the zabbix i can't use this data.

**Comment by tellurianx** [comment]
root@zabbix:/usr/lib/zabbix/externalscripts# ./emc_vnx_discovery.py --serial CKM00120201237 --ecom_ip 192.168.0.100 --ecom_user admin --ecom_pass "#1Password" --proc
{
    "data": [
        {
            "{#SPPERFDEVICEID}": "CLAR+CKM00120201237+FEAdapt+SP-A",
            "{#SPNAME}": "SPA",
            "{#SPIP}": "192.168.0.101",
            "{#SPDEVICEID}": "CLARiiON+CKM00120201237+SP_A"
        },
        {
            "{#SPPERFDEVICEID}": "CLAR+CKM00120201237+FEAdapt+SP-B",
            "{#SPNAME}": "SPB",
            "{#SPIP}": "192.168.0.102",
            "{#SPDEVICEID}": "CLARiiON+CKM00120201237+SP_B"
        }
    ]
}
root@zabbix:/usr/lib/zabbix/externalscripts#

**Comment by ktelep** [comment]
Very strange I spun up a Zabbix 3.0 Instance here and haven't had any
issues.

A couple more things to check:
1.  Delete any files generated in /tmp (particularly the
emc_vnx_discovery.log file)
2.  Run the script as the same user that the zabbix server runs as to
confirm that there isn't a strange python module.
3.  Check that the Timeout value for external scripts is set to 30 seconds

If you want to drop me an email (ktelep@gmail.com) we can coordinate a time
to do a webex and I'll take a look on your system to diagnose.

Kurt

**Comment by ktelep** [comment]
Closing this due to no response in troubleshooting, happy to help is anyone else runs into this issue again.

Note, the discovery script has additional logging info for exceptions, so check the emc_vnx_discovery.log file in /tmp for hints as to what the issue could be.

**Comment by naechin91004** [comment]
Zabbix 3.0 notwork
