### ISSUE TITLE
can you make VMAX template.

### ISSUE THREAD

**Issue by naechin91004** [ktelep/EMC-Zabbix-Integration#5]
I want make VMAX temlpate.
can you make VMAX template?

And can you python script using below data? that is vmax infomation

Symmetrix ID: 00000000000000

Symmetrix ID                     : 00000000000000
Pool Name                        : SAS600
Pool Type                        : Thin
Disk Location                    : Internal
Technology                       : FC
Dev Emulation                    : FBA
Dev Configuration                : RAID-5(3+1)
Pool State                       : Enabled
Compression State                : Disabled
# of Devices in Pool             : 392
# of Enabled Devices in Pool     : 392
# of Usable Tracks in Pool       : 1289831424
# of Allocated Tracks in Pool    : 1090596432
# of Tracks saved by compression :   0
# of Shared Tracks in Pool       :   0

Pool Utilization (%)             :  84
Pool Compression Ratio (%)       :   0
Max. Subscription Percent        : 100
Rebalance Variance               :   1%
Max devs per rebalance scan      : 256
Pool Reserved Capacity           : None

Enabled Devices(392):
  {

---

   Sym        Usable      Alloc       Free Full FLG Device
   Dev        Tracks     Tracks     Tracks  (%)  S  State

---

   0028      3222960    2753100     469860   85  .  Enabled
   0029      3222960    2749464     473496   85  .  Enabled
   002A      3222960    2749860     473100   85  .  Enabled
   002B      3222960    2755212     467748   85  .  Enabled
   002C      3222960    2751384     471576   85  .  Enabled
   002D      3222960    2715432     507528   84  .  Enabled
   002E      3222960    2741292     481668   85  .  Enabled
   002F      3222960    2738472     484488   84  .  Enabled
   0030      3223008    2737596     485412   84  .  Enabled
   0031      3223008    2755464     467544   85  .  Enabled
   0032      3223008    2756544     466464   85  .  Enabled
   0033      3223008    2743464     479544   85  .  Enabled
   0034      3223008    2752152     470856   85  .  Enabled
   0035      3223008    2753724     469284   85  .  Enabled
   0036      3223008    2757480     465528   85  .  Enabled
   0037      3223008    2756352     466656   85  .  Enabled
   0038      3223008    2750412     472596   85  .  Enabled
   0039      3223008    2752104     470904   85  .  Enabled
   003A      3223008    2753928     469080   85  .  Enabled
   003B      3223008    2756916     466092   85  .  Enabled
   003C      3223008    2754516     468492   85  .  Enabled
   003D      3223008    2755068     467940   85  .  Enabled
   003E      3223008    2754516     468492   85  .  Enabled
   003F      3223008    2754120     468888   85  .  Enabled
   0040      3223008    2744772     478236   85  .  Enabled
   0041      3223008    2749032     473976   85  .  Enabled
   0042      3223008    2751660     471348   85  .  Enabled
   0043      3223008    2747880     475128   85  .  Enabled
   0044      3223008    2733204     489804   84  .  Enabled
   0045      3223008    2751780     471228   85  .  Enabled
   0046      3223008    2756700     466308   85  .  Enabled
   0047      3223008    2755680     467328   85  .  Enabled
   0048      3223008    2748576     474432   85  .  Enabled
   0049      3223008    2748228     474780   85  .  Enabled
   004A      3223008    2757360     465648   85  .  Enabled
   004B      3223008    2731788     491220   84  .  Enabled
   004C      3223008    2751264     471744   85  .  Enabled
   004D      3223008    2748420     474588   85  .  Enabled
   004E      3223008    2749428     473580   85  .  Enabled
   004F      3223008    2747580     475428   85  .  Enabled
   0050      3298044    2805912     492132   85  .  Enabled
   0051      3298044    2804928     493116   85  .  Enabled
   0052      3298044    2806140     491904   85  .  Enabled
   0053      3298044    2804760     493284   85  .  Enabled
   0054      3298044    2803908     494136   85  .  Enabled
   0055      3298044    2806176     491868   85  .  Enabled
   0056      3298044    2803380     494664   85  .  Enabled
   0057      3298044    2804268     493776   85  .  Enabled
   0058      3298044    2805660     492384   85  .  Enabled
   0059      3298044    2803416     494628   85  .  Enabled
   005A      3298044    2805564     492480   85  .  Enabled
   005B      3298044    2805612     492432   85  .  Enabled
   005C      3298044    2805648     492396   85  .  Enabled
   005D      3298044    2804844     493200   85  .  Enabled
   005E      3298044    2805840     492204   85  .  Enabled
   005F      3298044    2805492     492552   85  .  Enabled
   0060      3298044    2805972     492072   85  .  Enabled
   0061      3298044    2806320     491724   85  .  Enabled
   0062      3298044    2806236     491808   85  .  Enabled
   0063      3298044    2804580     493464   85  .  Enabled
   0064      3298044    2805432     492612   85  .  Enabled
   0065      3298044    2806128     491916   85  .  Enabled
   0066      3298044    2806080     491964   85  .  Enabled
   0067      3298044    2804664     493380   85  .  Enabled
   0068      3298044    2805720     492324   85  .  Enabled
   0069      3298044    2806248     491796   85  .  Enabled
   006A      3298044    2804280     493764   85  .  Enabled
   006B      3298044    2805732     492312   85  .  Enabled
   006C      3298044    2803716     494328   85  .  Enabled
   006D      3298044    2805936     492108   85  .  Enabled
   006E      3298044    2804988     493056   85  .  Enabled
   006F      3298044    2805744     492300   85  .  Enabled
   0070      3298044    2805768     492276   85  .  Enabled
   0071      3298044    2806476     491568   85  .  Enabled
   0072      3298044    2806176     491868   85  .  Enabled
   0073      3298044    2806104     491940   85  .  Enabled
   0074      3298044    2806404     491640   85  .  Enabled
   0075      3298044    2805516     492528   85  .  Enabled
   0076      3298044    2805384     492660   85  .  Enabled
   0077      3298044    2803980     494064   85  .  Enabled
   0078      3298044    2802912     495132   84  .  Enabled
   0079      3298044    2805852     492192   85  .  Enabled
   007A      3298044    2805720     492324   85  .  Enabled
   007B      3298044    2806008     492036   85  .  Enabled
   007C      3298044    2804556     493488   85  .  Enabled
   007D      3298044    2806020     492024   85  .  Enabled
   007E      3298044    2805744     492300   85  .  Enabled
   007F      3298044    2806344     491700   85  .  Enabled
   0080      3298044    2805708     492336   85  .  Enabled
   0081      3298044    2805876     492168   85  .  Enabled
   0082      3298044    2806092     491952   85  .  Enabled
   0083      3298044    2806032     492012   85  .  Enabled
   0084      3298044    2806152     491892   85  .  Enabled
   0085      3298044    2806272     491772   85  .  Enabled
   0086      3298044    2804568     493476   85  .  Enabled
   0087      3298044    2805948     492096   85  .  Enabled
   0088      3298044    2805168     492876   85  .  Enabled
   0089      3298044    2805396     492648   85  .  Enabled
   008A      3298044    2806248     491796   85  .  Enabled
   008B      3298044    2805864     492180   85  .  Enabled
   008C      3298044    2805624     492420   85  .  Enabled
   008D      3298044    2806188     491856   85  .  Enabled
   008E      3298044    2806452     491592   85  .  Enabled
   008F      3298044    2805564     492480   85  .  Enabled
   0090      3298044    2805696     492348   85  .  Enabled
   0091      3298044    2803968     494076   85  .  Enabled
   0092      3298044    2805828     492216   85  .  Enabled
   0093      3298044    2806116     491928   85  .  Enabled
   0094      3298044    2805420     492624   85  .  Enabled
   0095      3298044    2805960     492084   85  .  Enabled
   0096      3298044    2806152     491892   85  .  Enabled
   0097      3298044    2805180     492864   85  .  Enabled
   0098      3298044    2806284     491760   85  .  Enabled
   0099      3298044    2806188     491856   85  .  Enabled
   009A      3298044    2805276     492768   85  .  Enabled
   009B      3298044    2805612     492432   85  .  Enabled
   009C      3298044    2803308     494736   84  .  Enabled
   009D      3298044    2806068     491976   85  .  Enabled
   009E      3298044    2805444     492600   85  .  Enabled
   009F      3298044    2806224     491820   85  .  Enabled
   00A0      3298044    2806032     492012   85  .  Enabled
   00A1      3298044    2806284     491760   85  .  Enabled
   00A2      3298044    2805900     492144   85  .  Enabled
   00A3      3298044    2804508     493536   85  .  Enabled
   00A4      3298044    2806404     491640   85  .  Enabled
   00A5      3298044    2805564     492480   85  .  Enabled
   00A6      3298044    2806140     491904   85  .  Enabled
   00A7      3298044    2806080     491964   85  .  Enabled
   00A8      3298044    2806560     491484   85  .  Enabled
   00A9      3298044    2804568     493476   85  .  Enabled
   00AA      3298044    2803344     494700   85  .  Enabled
   00AB      3298044    2806188     491856   85  .  Enabled
   00AC      3298044    2805804     492240   85  .  Enabled
   00AD      3298044    2805912     492132   85  .  Enabled
   00AE      3298044    2806152     491892   85  .  Enabled
   00AF      3298044    2806200     491844   85  .  Enabled
   00B0      3298044    2806332     491712   85  .  Enabled
   00B1      3298044    2804712     493332   85  .  Enabled
   00B2      3298044    2806308     491736   85  .  Enabled
   00B3      3298044    2802600     495444   84  .  Enabled
   00B4      3298044    2806368     491676   85  .  Enabled
   00B5      3298044    2804508     493536   85  .  Enabled
   00B6      3298044    2805216     492828   85  .  Enabled
   00B7      3298044    2804832     493212   85  .  Enabled
   00B8      3298044    2806128     491916   85  .  Enabled
   00B9      3298044    2805564     492480   85  .  Enabled
   00BA      3298044    2805996     492048   85  .  Enabled
   00BB      3298044    2806044     492000   85  .  Enabled
   00BC      3298044    2805792     492252   85  .  Enabled
   00BD      3298044    2804880     493164   85  .  Enabled
   00BE      3298044    2806224     491820   85  .  Enabled
   00BF      3298044    2805720     492324   85  .  Enabled
   00C0      3298044    2805648     492396   85  .  Enabled
   00C1      3298044    2804076     493968   85  .  Enabled
   00C2      3298044    2806260     491784   85  .  Enabled
   00C3      3298044    2805948     492096   85  .  Enabled
   00C4      3298044    2806200     491844   85  .  Enabled
   00C5      3298044    2805828     492216   85  .  Enabled
   00C6      3298044    2804304     493740   85  .  Enabled
   00C7      3298044    2806056     491988   85  .  Enabled
   00C8      3298044    2805816     492228   85  .  Enabled
   00C9      3298044    2806020     492024   85  .  Enabled
   00CA      3298044    2802708     495336   84  .  Enabled
   00CB      3298044    2806068     491976   85  .  Enabled
   00CC      3298044    2803824     494220   85  .  Enabled
   00CD      3298044    2802336     495708   84  .  Enabled
   00CE      3298044    2806068     491976   85  .  Enabled
   00CF      3298044    2804844     493200   85  .  Enabled
   00D0      3298044    2804532     493512   85  .  Enabled
   00D1      3298044    2805576     492468   85  .  Enabled
   00D2      3298044    2804580     493464   85  .  Enabled
   00D3      3298044    2805120     492924   85  .  Enabled
   00D4      3298044    2805600     492444   85  .  Enabled
   00D5      3298044    2806200     491844   85  .  Enabled
   00D6      3298044    2804892     493152   85  .  Enabled
   00D7      3298044    2805624     492420   85  .  Enabled
   00D8      3298044    2806260     491784   85  .  Enabled
   00D9      3298044    2805552     492492   85  .  Enabled
   00DA      3298044    2805564     492480   85  .  Enabled
   00DB      3298044    2800116     497928   84  .  Enabled
   00DC      3298044    2806056     491988   85  .  Enabled
   00DD      3298044    2804928     493116   85  .  Enabled
   00DE      3298044    2806128     491916   85  .  Enabled
   00DF      3298044    2804736     493308   85  .  Enabled
   00E0      3298044    2805228     492816   85  .  Enabled
   00E1      3298044    2803668     494376   85  .  Enabled
   00E2      3298044    2805360     492684   85  .  Enabled
   00E3      3298044    2805828     492216   85  .  Enabled
   00E4      3298044    2805408     492636   85  .  Enabled
   00E5      3298044    2805828     492216   85  .  Enabled
   00E6      3298044    2804568     493476   85  .  Enabled
   00E7      3298044    2805756     492288   85  .  Enabled
   00E8      3298044    2805612     492432   85  .  Enabled
   00E9      3298044    2805108     492936   85  .  Enabled
   00EA      3298044    2803800     494244   85  .  Enabled
   00EB      3298044    2805624     492420   85  .  Enabled
   00EC      3298044    2805264     492780   85  .  Enabled
   00ED      3298044    2805924     492120   85  .  Enabled
   00EE      3298044    2805792     492252   85  .  Enabled
   00EF      3298044    2806296     491748   85  .  Enabled
   00F0      3298044    2806596     491448   85  .  Enabled
   00F1      3298044    2806176     491868   85  .  Enabled
   00F2      3298044    2806224     491820   85  .  Enabled
   00F3      3298044    2806260     491784   85  .  Enabled
   00F4      3298044    2806632     491412   85  .  Enabled
   00F5      3298044    2803632     494412   85  .  Enabled
   00F6      3298044    2805744     492300   85  .  Enabled
   00F7      3298044    2806044     492000   85  .  Enabled
   00F8      3298044    2804856     493188   85  .  Enabled
   00F9      3298044    2806248     491796   85  .  Enabled
   00FA      3298044    2806140     491904   85  .  Enabled
   00FB      3298044    2805348     492696   85  .  Enabled
   00FC      3298044    2805816     492228   85  .  Enabled
   00FD      3298044    2805948     492096   85  .  Enabled
   00FE      3298044    2806260     491784   85  .  Enabled
   00FF      3298044    2805372     492672   85  .  Enabled
   0100      3298044    2805876     492168   85  .  Enabled
   0101      3298044    2805684     492360   85  .  Enabled
   0102      3298044    2805348     492696   85  .  Enabled
   0103      3298044    2804976     493068   85  .  Enabled
   0104      3298044    2805612     492432   85  .  Enabled
   0105      3298044    2806200     491844   85  .  Enabled
   0106      3298044    2805252     492792   85  .  Enabled
   0107      3298044    2805900     492144   85  .  Enabled
   0108      3298044    2805984     492060   85  .  Enabled
   0109      3298044    2805972     492072   85  .  Enabled
   010A      3298044    2805360     492684   85  .  Enabled
   010B      3298044    2805480     492564   85  .  Enabled
   010C      3298044    2806152     491892   85  .  Enabled
   010D      3298044    2806248     491796   85  .  Enabled
   010E      3298044    2805636     492408   85  .  Enabled
   010F      3298044    2805672     492372   85  .  Enabled
   0110      3298044    2804892     493152   85  .  Enabled
   0111      3298044    2804928     493116   85  .  Enabled
   0112      3298044    2804868     493176   85  .  Enabled
   0113      3298044    2803896     494148   85  .  Enabled
   0114      3298044    2806140     491904   85  .  Enabled
   0115      3298044    2802624     495420   84  .  Enabled
   0116      3298044    2805936     492108   85  .  Enabled
   0117      3298044    2805960     492084   85  .  Enabled
   0118      3298044    2804028     494016   85  .  Enabled
   0119      3298044    2805504     492540   85  .  Enabled
   011A      3298044    2805528     492516   85  .  Enabled
   011B      3298044    2805528     492516   85  .  Enabled
   011C      3298044    2805768     492276   85  .  Enabled
   011D      3298044    2806188     491856   85  .  Enabled
   011E      3298044    2805804     492240   85  .  Enabled
   011F      3298044    2806152     491892   85  .  Enabled
   0120      3298044    2805888     492156   85  .  Enabled
   0121      3298044    2805852     492192   85  .  Enabled
   0122      3298044    2805732     492312   85  .  Enabled
   0123      3298044    2805288     492756   85  .  Enabled
   0124      3298044    2806392     491652   85  .  Enabled
   0125      3298044    2805900     492144   85  .  Enabled
   0126      3298044    2805900     492144   85  .  Enabled
   0127      3298044    2805684     492360   85  .  Enabled
   02FE      3298044    2759244     538800   83  .  Enabled
   02FF      3298044    2749992     548052   83  .  Enabled
   0300      3298044    2751180     546864   83  .  Enabled
   0301      3298044    2751756     546288   83  .  Enabled
   0302      3298044    2749884     548160   83  .  Enabled
   0303      3298044    2750376     547668   83  .  Enabled
   0304      3298044    2751528     546516   83  .  Enabled
   0305      3298044    2752656     545388   83  .  Enabled
   0306      3298044    2759052     538992   83  .  Enabled
   0307      3298044    2752920     545124   83  .  Enabled
   0308      3298044    2750784     547260   83  .  Enabled
   0309      3298044    2755476     542568   83  .  Enabled
   030A      3298044    2749752     548292   83  .  Enabled
   030B      3298044    2750892     547152   83  .  Enabled
   030C      3298044    2761740     536304   83  .  Enabled
   030D      3298044    2751024     547020   83  .  Enabled
   030E      3298044    2749200     548844   83  .  Enabled
   030F      3298044    2750976     547068   83  .  Enabled
   0310      3298044    2752452     545592   83  .  Enabled
   0311      3298044    2751132     546912   83  .  Enabled
   0312      3298044    2749860     548184   83  .  Enabled
   0313      3298044    2755752     542292   83  .  Enabled
   0314      3298044    2754348     543696   83  .  Enabled
   0315      3298044    2750832     547212   83  .  Enabled
   0316      3298044    2750844     547200   83  .  Enabled
   0317      3298044    2750772     547272   83  .  Enabled
   0318      3298044    2755464     542580   83  .  Enabled
   0319      3298044    2751720     546324   83  .  Enabled
   031A      3298044    2757036     541008   83  .  Enabled
   031B      3298044    2754132     543912   83  .  Enabled
   031C      3298044    2755440     542604   83  .  Enabled
   031D      3298044    2749392     548652   83  .  Enabled
   031E      3298044    2751696     546348   83  .  Enabled
   031F      3298044    2751708     546336   83  .  Enabled
   0320      3298044    2750316     547728   83  .  Enabled
   0321      3298044    2759412     538632   83  .  Enabled
   0322      3298044    2759112     538932   83  .  Enabled
   0323      3298044    2761128     536916   83  .  Enabled
   0324      3298044    2761788     536256   83  .  Enabled
   0325      3298044    2752212     545832   83  .  Enabled
   0326      3298044    2756664     541380   83  .  Enabled
   0327      3298044    2756136     541908   83  .  Enabled
   0328      3298044    2761224     536820   83  .  Enabled
   0329      3298044    2754732     543312   83  .  Enabled
   032A      3298044    2750340     547704   83  .  Enabled
   032B      3298044    2762832     535212   83  .  Enabled
   032C      3298044    2752704     545340   83  .  Enabled
   032D      3298044    2760132     537912   83  .  Enabled
   032E      3298044    2749824     548220   83  .  Enabled
   032F      3298044    2757444     540600   83  .  Enabled
   0330      3298044    2765256     532788   83  .  Enabled
   0331      3298044    2757024     541020   83  .  Enabled
   0332      3298044    2756028     542016   83  .  Enabled
   0333      3298044    2751348     546696   83  .  Enabled
   0334      3298044    2752188     545856   83  .  Enabled
   0335      3298044    2748612     549432   83  .  Enabled
   0336      3298044    2753364     544680   83  .  Enabled
   0337      3298044    2756388     541656   83  .  Enabled
   0338      3298044    2761932     536112   83  .  Enabled
   0339      3298044    2758908     539136   83  .  Enabled
   033A      3298044    2758476     539568   83  .  Enabled
   033B      3298044    2763060     534984   83  .  Enabled
   033C      3298044    2761044     537000   83  .  Enabled
   033D      3298044    2750844     547200   83  .  Enabled
   033E      3298044    2754348     543696   83  .  Enabled
   033F      3298044    2759532     538512   83  .  Enabled
   0340      3298044    2750832     547212   83  .  Enabled
   0341      3298044    2754348     543696   83  .  Enabled
   0342      3298044    2749236     548808   83  .  Enabled
   0343      3298044    2751396     546648   83  .  Enabled
   0344      3298044    2759196     538848   83  .  Enabled
   0345      3298044    2755212     542832   83  .  Enabled
   0346      3298044    2759052     538992   83  .  Enabled
   0347      3298044    2764032     534012   83  .  Enabled
   0348      3298044    2755020     543024   83  .  Enabled
   0349      3298044    2758848     539196   83  .  Enabled
   034A      3298044    2756316     541728   83  .  Enabled
   034B      3298044    2758740     539304   83  .  Enabled
   034C      3298044    2752368     545676   83  .  Enabled
   034D      3298044    2752752     545292   83  .  Enabled
   034E      3298044    2750352     547692   83  .  Enabled
   034F      3298044    2763360     534684   83  .  Enabled
   0350      3298044    2753232     544812   83  .  Enabled
   0351      3298044    2753676     544368   83  .  Enabled
   0352      3298044    2764908     533136   83  .  Enabled
   0353      3298044    2755344     542700   83  .  Enabled
   0354      3298044    2750832     547212   83  .  Enabled
   0355      3298044    2759424     538620   83  .  Enabled
   0356      3298044    2757576     540468   83  .  Enabled
   0357      3298044    2750892     547152   83  .  Enabled
   0358      3298044    2750784     547260   83  .  Enabled
   0359      3298044    2759736     538308   83  .  Enabled
   035A      3298044    2762172     535872   83  .  Enabled
   035B      3298044    2749476     548568   83  .  Enabled
   035C      3298044    2750820     547224   83  .  Enabled
   035D      3298044    2750136     547908   83  .  Enabled
   035E      3298044    2754312     543732   83  .  Enabled
   035F      3298044    2758824     539220   83  .  Enabled
   0360      3298044    2763264     534780   83  .  Enabled
   0361      3298044    2754708     543336   83  .  Enabled
   0362      3298044    2750604     547440   83  .  Enabled
   0363      3298044    2751624     546420   83  .  Enabled
   0364      3298044    2750724     547320   83  .  Enabled
   0365      3298044    2749548     548496   83  .  Enabled
   0366      3298044    2750196     547848   83  .  Enabled
   0367      3298044    2750436     547608   83  .  Enabled
   0368      3298044    2750772     547272   83  .  Enabled
   0369      3298044    2752404     545640   83  .  Enabled
   036A      3298044    2757492     540552   83  .  Enabled
   036B      3298044    2753592     544452   83  .  Enabled
   036C      3298044    2751636     546408   83  .  Enabled
   036D      3298044    2750340     547704   83  .  Enabled
   036E      3298044    2750556     547488   83  .  Enabled
   036F      3298044    2759676     538368   83  .  Enabled
   0370      3298044    2761596     536448   83  .  Enabled
   0371      3298044    2749512     548532   83  .  Enabled
   0372      3298044    2763900     534144   83  .  Enabled
   0373      3298044    2762016     536028   83  .  Enabled
   0374      3298044    2749932     548112   83  .  Enabled
   0375      3298044    2752044     546000   83  .  Enabled
   0376      3298044    2751768     546276   83  .  Enabled
   0377      3298044    2750808     547236   83  .  Enabled
   0378      3298044    2764344     533700   83  .  Enabled
   0379      3298044    2752572     545472   83  .  Enabled
   037A      3298044    2754960     543084   83  .  Enabled
   037B      3298044    2752104     545940   83  .  Enabled
   037C      3298044    2763804     534240   83  .  Enabled
   037D      3298044    2752704     545340   83  .  Enabled
   037E      3298044    2756544     541500   83  .  Enabled
   037F      3298044    2763384     534660   83  .  Enabled
   0380      3298044    2751684     546360   83  .  Enabled
   0381      3298044    2750544     547500   83  .  Enabled
   0382      3298044    2751132     546912   83  .  Enabled
   0383      3298044    2749488     548556   83  .  Enabled
   0384      3298044    2761152     536892   83  .  Enabled
   0385      3298044    2749788     548256   83  .  Enabled
          ---------- ---------- ---------- ----
   Tracks 1289831424 1090596432  199234992   84
  }

Pool Bound Thin Devices(83):
  {

---

```
                  Pool          Pool          Total        Compressed
```

   Sym   FLG       Total Sub      Allocated      Written       Size/Ratio
   Dev    T       Tracks (%)     Tracks (%)     Tracks (%)     Tracks (%)

---

   0175   B     16776000   1   16778688 100   16775041 100   16778688   0
   017D   B     16776000   1   16778700 100   16546852  99   16778700   0
   0185   B     16776000   1   16778688 100   14868951  89   16778688   0
   018D   B     16776000   1   16778676 100   14378270  86   16778676   0
   0195   B     16776000   1   16778688 100    1902486  11   16778688   0
   019D   B     16776000   1   16778676 100   16775041 100   16778676   0
   01A5   B     16776000   1   16778676 100   16774905 100   16778676   0
   01AD   B     16776000   1   16778664 100   16755702 100   16778664   0
   01B5   B     16776000   1   16778700 100    7956388  47   16778700   0
   01BD   B     16776000   1   16778700 100   16191236  97   16778700   0
   01C5   B     16776000   1   16778688 100    2732583  16   16778688   0
   01CD   B     16776000   1   16778688 100       6865   0   16778688   0
   01D5   B     16776000   1   16778700 100       6481   0   16778700   0
   01DD   B     16776000   1   16778700 100     114130   1   16778700   0
   01E5   B     16776000   1   16778676 100   16647248  99   16778676   0
   01ED   B     16776000   1   16778676 100   16614530  99   16778676   0
   01F5   B     16776000   1   16778688 100   13435878  80   16778688   0
   01FD   B     16776000   1   16778700 100   16775041 100   16778700   0
   0205   B     16776000   1   16778700 100   16775041 100   16778700   0
   020D   B     16776000   1   16778688 100   16775041 100   16778688   0
   0215   B     16776000   1   16778676 100   16775041 100   16778676   0
   021D   B     16776000   1   16778688 100   16775041 100   16778688   0
   0225   B     16776000   1   16778676 100   16775041 100   16778676   0
   022D   B     16776000   1   16778700 100   16775041 100   16778700   0
   0235   B     16776000   1   16778676 100   16775041 100   16778676   0
   023D   B     16776000   1   16778688 100   16775041 100   16778688   0
   0245   B     16776000   1   16778712 100   16770010 100   16778712   0
   024D   B     16776000   1   16778712 100    4914811  29   16778712   0
   0255   B     16776000   1   16778700 100    6617735  39   16778700   0
   025D   B     16776000   1   16778700 100   16775041 100   16778700   0
   0265   B     16776000   1   16778700 100   16775041 100   16778700   0
   026D   B     16776000   1   16778688 100   16775041 100   16778688   0
   0275   B     16776000   1   16778664 100   13123867  78   16778664   0
   027D   B     16776000   1   16778676 100   16742820 100   16778676   0
   0285   B     16776000   1   16778712 100   16774153 100   16778712   0
   028D   B     16776000   1   16778712 100       3205   0   16778712   0
   0295   B     16776000   1   16778688 100    4283638  26   16778688   0
   029D   B     16776000   1   16778676 100   16775041 100   16778676   0
   02A5   B     16776000   1   16778688 100   16775041 100   16778688   0
   02AD   B     16776000   1   16778676 100   16775041 100   16778676   0
   02B5   B     16776000   1   16778676 100   16775041 100   16778676   0
   02BD   B     16776000   1   16778676 100   16774891 100   16778676   0
   02C5   B     16776000   1   16778688 100   16775041 100   16778688   0
   02CD   B     16776000   1   16778568 100   16774947 100   16778568   0
   02D5   B     16776000   1   16778664 100    7561325  45   16778664   0
   02DD   B     16776000   1   16778688 100   16753367 100   16778688   0
   02E5   B     16776000   1   16778700 100   16774906 100   16778700   0
   02ED   B     16776000   1   16778664 100    1866716  11   16778664   0
   02F5   B      6291000   0    6292020 100    2088257  33    6292020   0
   02F8   B      2097000   0    2097312 100    1803411  86    2097312   0
   02F9   B      2097000   0    2097360 100    1127286  54    2097360   0
   02FA   B      2097000   0    2097300 100    1966210  94    2097300   0
   02FB   B        16500   0      16512 100        515   3      16512   0
   02FC   B        16500   0      16512 100        515   3      16512   0
   02FD   B        16500   0      16512 100        515   3      16512   0
   0386   B       838800   0     838968 100     409676  49     838968   0
   038A   B       838800   0     838968 100     162723  19     838968   0
   038E   B      1258200   0    1258452 100     928548  74    1258452   0
   0394   B      1258200   0    1258452 100     654198  52    1258452   0
   039A   B     16776000   1   16778892 100       1161   0   16778892   0
   03A2   B     16776000   1   16778856 100     386073   2   16778856   0
   03AA   B     16776000   1   16778868 100    5476610  33   16778868   0
   03B2   B     16776000   1   16778868 100        516   0   16778868   0
   03BA   B     16776000   1   16778868 100        516   0   16778868   0
   03C2   B     16776000   1   16778856 100        516   0   16778856   0
   03CA   B     16776000   1   16778868 100   16209727  97   16778868   0
   03D2   B     16776000   1   16778868 100   16775426 100   16778868   0
   03DA   B     16776000   1   16778856 100   16753580 100   16778856   0
   03E2   B     16776000   1   16778880 100    9328144  56   16778880   0
   03EA   B     16776000   1   16778880 100   16775426 100   16778880   0
   03F2   B     16776000   1   16778904 100    7899155  47   16778904   0
   03FA   B     16776000   1   16778904 100   16766202 100   16778904   0
   0402   B     16776000   1   16778892 100     764707   5   16778892   0
   040A   B     16776000   1   16778856 100   16740629 100   16778856   0
   0412   B     16776000   1   16778856 100       1130   0   16778856   0
   041A   B        16500   0      16512 100        516   3      16512   0
   041B   B        16500   0      16512 100        516   3      16512   0
   041C   B        16500   0      16512 100        516   3      16512   0
   041D   B        16500   0      16512 100        516   3      16512   0
   041E   B        16500   0      16512 100        516   3      16512   0
   041F   B        16500   0      16512 100        516   3      16512   0
   0420   B       838800   0        672   0        549   0        672   0
   0424   B       838800   0        696   0        557   0        696   0
              ---------- --- ---------- --- ---------- --- ---------- ---
   Tracks     1092266100  85 1090767672 100  762420249  70 1090767672   0
  }

No Other-Pool Bound Thin Devices have allocations in Device Pool SAS600

**Comment by ktelep** [comment]
As of today, this integration only supports VNX.  I am considering adding VMAX support however it will require adding more than just a template.  With the newer VMAX's there is also a RESTful interface that could be used in place of the WBEM methodology used for VNX.

It is on the futures list, however I cannot provide a date when it will actually be completed
