### ISSUE TITLE
Exeption error in manual discovery

### ISSUE THREAD

**Issue by polcape** [ktelep/EMC-Zabbix-Integration#7]
I have Zabbix 3.0 installed on Ubuntu 14.04

The discovery script run from Zabbix seem to working fine (in the /tmp/emc_vnx_discovery.log i don't have any error).
If I run manually the same script with, for example, ./emc_vnx_discovery.py --serial serialNumber --ecom_ip 'xxx.xxx.xxx.xxx' --ecom_user admin --ecom_pass 'password' -a
i get this error:

2016-02-24 11:12:34,127 INFO 973 Building WBEM Connection to https://172.258.1.47:5989
2016-02-24 11:12:34,127 INFO 973 Array hardware discovery started
2016-02-24 11:12:34,141 ERROR 973 Uncaught exception: (0, 'Socket error: [Errno -2] Name or service not known')
None

It is normal?
Is there a debuggin way to view is the script working fine?

**Comment by ktelep** [comment]
I'm assuming based on the separate issue that you opened you were able to get past this.  It appears there is an error in the IP address that you have defined as 172.158.1.47 is invalid.

I need to add some sanity checks around IP addresses and some better failure logic.

**Comment by polcape** [comment]
Yes, I have solved this problem by myself. And I have open other issue after.
You can close this.

Thanks
