### ISSUE TITLE
Error in stats collection

### ISSUE THREAD

**Issue by polcape** [ktelep/EMC-Zabbix-Integration#8]
I have Zabbix 3.0 installed on Ubuntu 14.04
I have install this integration, for get data from VNX 5300, and I have some problems.

The discovery script run from Zabbix seem to working fine (in the /tmp/emc_vnx_discovery.log i don't have any error), it get 3317 item.

But when i go to view the last data from Zabbix interface in the stat collection there is some errors show as last value.

For example the last value of Physical Disk Stats Collection is 

Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/emc_vnx_stats.py", line 628, in <module>
    main()
  File "/usr/lib/zabbix/externalscripts/emc_vnx_stats.py", line 604, in main
    args.ecom_user, args.ecom_pass)
  File "/usr/lib/zabbix/externalscripts/emc_vnx_stats.py", line 270, in disk_stats_query
    ecom_user, ecom_pass)
  File "/usr/lib/zabbix/externalscripts/emc_vnx_stats.py", line 141, in get_stats
    StatisticsFormat=pywbem.Uint16(2))
  File "/usr/local/lib/python2.7/dist-packages/pywbem/cim_operations.py", line 801, in InvokeMethod
    result = self.methodcall(MethodName, obj, **params)
  File "/usr/local/lib/python2.7/dist-packages/pywbem/cim_operations.py", line 362, in methodcall
    raise CIMError(code, tt[0][1]['DESCRIPTION'])
pywbem.cim_operations.CIMError: (15, u'The query is not valid for the specified query language. (com.emc.cmp.osls.se.array.func.EMC_BlockStatisticsService.GetStatisticsCollection():2622 C:ERROR_CLASS_SOFTWARE F:ERROR_FAMILY_OPERATION_NOT_AVAILABLE Statistics Service is not enabled for array <Array type="CLARiiON" encoding="String" value="serialOfVNX" />)')

A similar error I get from Collect Pool IO Stats, Storage Processor Stats Collection, Volume Stats Collection.
Even if there is this error in Collect Pool IO Stats, Zabbix get all the pools. But in storage processors and in volumes it get no data.

Please help me.
Thanks

**Comment by ktelep** [comment]
It looks like you do not have Block Statistics Logging enabled on the array, note that this is different then having Analyzer collecting data on the array.

From the error you listed:   ERROR_CLASS_SOFTWARE F:ERROR_FAMILY_OPERATION_NOT_AVAILABLE *_Statistics Service is not enabled for array *_

Here are the steps to enable statistics logging:    https://community.emc.com/docs/DOC-24564   Once this is done you should start to see data coming in.

**Comment by ktelep** [comment]
Need to add confirmation that Statistics Logging is already enabled on the array and error out appropriately.

**Comment by polcape** [comment]
Thanks. The Statistics Logging checkbox was disabled.

Now I have enabled the options but I see again the previous error. I need to wait some hours or the modification is immediate?

**Comment by ktelep** [comment]
It should start working pretty quickly.   Let me know if it isn't after 5-6 hours.

**Comment by polcape** [comment]
I have add the monitoring with Zabbix to the EMC CX4-120 and to the ENC VNX 5300
With VNX 5300 I have no problem and all item get data.

With the CX4 there are the errors previously reported in Physical Disk Stats Collection, Collect Pool IO Stats, Storage Processor Stats Collection,     Volume Stats Collection

Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/emc_vnx_stats.py", line 628, in <module>
    main()
  File "/usr/lib/zabbix/externalscripts/emc_vnx_stats.py", line 604, in main
    args.ecom_user, args.ecom_pass)
  File "/usr/lib/zabbix/externalscripts/emc_vnx_stats.py", line 270, in disk_stats_query
    ecom_user, ecom_pass)
  File "/usr/lib/zabbix/externalscripts/emc_vnx_stats.py", line 141, in get_stats
    StatisticsFormat=pywbem.Uint16(2))
  File "/usr/local/lib/python2.7/dist-packages/pywbem/cim_operations.py", line 801, in InvokeMethod
    result = self.methodcall(MethodName, obj, **params)
  File "/usr/local/lib/python2.7/dist-packages/pywbem/cim_operations.py", line 362, in methodcall
    raise CIMError(code, tt[0][1]['DESCRIPTION'])
pywbem.cim_operations.CIMError: (15, u'The query is not valid for the specified query language. (com.emc.cmp.osls.se.array.func.EMC_BlockStatisticsService.GetStatisticsCollection():2622 C:ERROR_CLASS_SOFTWARE F:ERROR_FAMILY_OPERATION_NOT_AVAILABLE Statistics Service is not enabled for array <Array type="CLARiiON" encoding="String" value="serialStorage" />)')

The Statistics Logging checkbox was enabled on both.
Any advice?

**Comment by polcape** [comment]
Update.
Now, after a day there are all the datas for all the items.
Probably I have to attend some hours.

Thanks
